spring:
  jackson:
    serialization:
      fail-on-empty-beans: false

  datasource:
    url: jdbc:mysql://localhost:65142/cafe?useTimezone=true&serverTimezone=UTC&useLegacyDate
    username: root
    password: 134546
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
    database: mysql
server:

