  server:
    port: 8080

  spring:
    datasource:
      url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: 134546
      driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update


